### ISSUE TITLE
At stable/zed manila tests (using ganesha) fail with stale file handle

### ISSUE THREAD

**Issue by ajkavanagh** [openstack-charmers/zaza-openstack-tests#1107]
The test scenario at https://github.com/openstack-charmers/zaza-openstack-tests/blob/d78e2f40000d8501536997b153a7b0b739a741c4/zaza/openstack/charm_tests/manila/tests.py#L284 uses `rm` to remove a file on the share on one instance, then writes a new file.  This causes the NFS server to create a new inode, and the existing inode on the other instance goes stale.  It eventually, after some time *will* recover, but this is a feature of the NFS server, rather than testing whether the system is set up appropriately.

By using `truncate -s 0` instead of `rm` the file can be erased and and re-written to, which maintains the file handle stopping the breakage.

Whether this is "valid" is the question.

I'll also attempt to change the order of the operations so that the file is deleted and then the share is remounted at: https://github.com/openstack-charmers/zaza-openstack-tests/blob/d78e2f40000d8501536997b153a7b0b739a741c4/zaza/openstack/charm_tests/manila/tests.py#L395C22-L395C22

**Comment by coreycb** [comment]
Good work finding this. This seems to be a commonly known behavior with NFS. I think a test adjustment like you suggested makes sense.

**Comment by ajkavanagh** [comment]
This is tested by https://review.opendev.org/c/openstack/charm-manila/+/884382

**Comment by freyes** [comment]
Closed by #1111
