### ISSUE TITLE
Octavia payload test appears not to work

### ISSUE THREAD

**Issue by thedac** [openstack-charmers/zaza-openstack-tests#27]
The Octavia payload [0] test seems to not work.

At a minimum, we will need to add port 80 access to the default (admin_domain) security group.

The member node will also need to listen on port 80. This may be a greater challenge. Either we need to ssh onto the node and install apache or we need an image with apache running.

[0] https://github.com/openstack-charmers/zaza-openstack-tests/commit/7140e4e064466664ed0e6acca68467bcc7658a6c

**Comment by fnordahl** [comment]
The corresponding change to the charm is here https://review.opendev.org/#/c/666828/

**Comment by thedac** [comment]
Sorry for the noise
