### ISSUE TITLE
TrilioBaseTest timeout needs extending

### ISSUE THREAD

**Issue by wolsen** [openstack-charmers/zaza-openstack-tests#593]
As seen in https://review.opendev.org/c/openstack/charm-trilio-data-mover/+/794844/, there are some false failures in the tests which appear to be related to the timeout for taking a snapshot.

After having looked through the logs for the test failures, I believe that the problem is that the test times out after 12 minutes [0] but the snapshot sequence takes nearly the full time:

1. Freeze instance
2. Snapshot
3. Thaw instance
4. Upload snapshot
5. perform a disk check of snapshot images

Log snippets [here](https://paste.ubuntu.com/p/GtzSMwY3bD/)

The freeze is issued and there's a 3 second window between the freeze completing and the snapshot being issued. The snapshot itself takes ~25 seconds. The upload begins almost 1 minute later, and takes a bit over 7 minutes. Finalizing occurs and takes about 7 seconds. The final snapshot disk validation starts about a minute later and takes approximately 35 seconds.

In total, the timings on the data-mover piece from the time the sequence starts to complete finishes about 15 seconds ahead of when the test times out. However, we can see long delays between one step of the sequence and the next step of the sequence which leads me to believe that the snapshot process was actually completed, but requiring some additional metadata updates that was being slow at the dm-api layer.

I believe a simple, albeit ugly fix for CI testing is to increase the timeout from 12 minutes to something around 15 minutes.

**Comment by gnuoy** [comment]
Thank you for  the analysis, I've raised https://github.com/openstack-charmers/zaza-openstack-tests/pull/594 to bump the snapshot timeout.

**Comment by ajkavanagh** [comment]
Closed by #594
